### ISSUE TITLE
Thing is created but authorization fails

### ISSUE THREAD

**Issue by gomezago** [datacentricdesign/bucket#17]
When using Thing - Create (REST API) the thing is being created, but the response indicates that the authorization failed. Maybe things are created before checking the authorization?

**Comment by jackybourgeois** [comment]
Thanks @gomezago, if you can replicate it, it would be great to have some snapshot. I believe it happens when finalising the creation of the thing (so you are authorised), but somehow an error is not caught properly and it ends up being caught by the for the wrong error message. If you can add the time of the error, I could have a look also in the logs.
